{% set name = "mujoco" %}
{% set namecxx = "mujoco-cxx" %}
{% set namepython = "mujoco-python" %}
{% set version = "2.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/deepmind/mujoco/archive/refs/tags/{{ version }}.tar.gz
  sha256: a9cc2c09c0d462c270d895cb06ffc1a78897117430f88efa978ec3b7bb454488
  patches:
    - python_remove_avx.patch
    - python_remove_werror.patch
    - cxx_devendor.patch
    - python_devendor.patch
    - ccd_vec3_origin_link_problem.patch
    - disable_copy_cxx_files_in_python_package.patch
    - do_not_install_via_pip.patch
    - macosmin1014.patch


build:
  number: 0
  skip: true  # [py<37]

outputs:
  - name: {{ namecxx }}
    script: build_cxx.sh  # [unix]
    script: bld_cxx.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage(namecxx, max_pin='x.x.x') }}
      # abseil-cpp is used only for tests, we can 
      # safely ignore its run_exports
      ignore_run_exports:
        - abseil-cpp
    requirements:
      build:
        - cmake
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make                                   # [not win]
        - ninja
        - clang 14  # [win]
      host:
        - eigen
        - qhull
        - tinyxml2
        - libccd-double
        - abseil-cpp
        - lodepng
      run:
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

    test:
      commands:
        - test -f ${PREFIX}/include/mujoco/mujoco.h  # [not win]
        - test -f ${PREFIX}/lib/libmujoco${SHLIB_EXT}  # [unix]
        - test -f ${PREFIX}/bin/mujoco_plugin/libcable${SHLIB_EXT}  # [unix]
        - if not exist %LIBRARY_INC%\\mujoco\\mujoco.h exit 1  # [win]
        - if not exist %LIBRARY_LIB%\\mujoco.lib exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\mujoco.dll exit 1  # [win]
        - if not exist %LIBRARY_BIN%\\mujoco_plugin\\cable.dll exit 1  # [win]
        - if exist %LIBRARY_BIN%\\mujoco_plugin\\cable.lib exit 1  # [win]


  - name: {{ namepython }}
    build:
      skip: true  # [ppc64le]
    script: build_py.sh  # [unix]
    script: bld_py.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make                                   # [not win]
        - ninja                                  # [win]
        - cmake
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - numpy                                  # [build_platform != target_platform]
        - pip                                    # [build_platform != target_platform]
        - setuptools                             # [build_platform != target_platform]
        - absl-py                                # [build_platform != target_platform]
        - clang 14                               # [win]
        - bash                                   # [not win]
        - posix                                  # [win]
      host:
        - {{ pin_subpackage(namecxx, exact=True) }}
        - eigen
        - abseil-cpp
        - python
        - pip
        - setuptools
        - pybind11
        - pybind11-abi
        - numpy
        - absl-py
        - pyglfw
        - pyopengl
      run:
        - {{ pin_subpackage(namecxx, exact=True) }}
        - python
        - numpy
        - absl-py
        - pyglfw
        - pyopengl
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]
    test:
      imports:
        - mujoco
      requires:
        - pytest
        - pip
      commands:
        - pytest --pyargs mujoco -v -k "not render"
        - pip check

  - name: {{ name }}
    requirements:
      run:
        - {{ pin_subpackage(namecxx, exact=True) }}
        - {{ pin_subpackage(namepython, max_pin='x.x.x') }}
    test:
      imports:
        - mujoco

about:
  home: https://github.com/deepmind/mujoco
  license: Apache-2.0
  license_file:
    - LICENSE
    - build/_deps/tinyobjloader-src/LICENSE
  summary: Multi-Joint dynamics with Contact. A general purpose multi-body dynamics simulator.

extra:
  recipe-maintainers:
    - traversaro
